version: 2

updates:
  - package-ecosystem: "npm"
    directory: "./app"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows/"
    schedule:
      interval: "monthly"
