FROM node:20-alpine
RUN apk add bash
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN pnpm config set store-dir /tmp/pnpm/store

WORKDIR /app
COPY package.json pnpm-lock.yaml wait-for-it.sh ./
RUN chmod 777 ./wait-for-it.sh
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile -r
COPY . .
RUN pnpm run build

EXPOSE 3000
# RUN chown -R node /app
# USER node
CMD [ "pnpm", "start" ]