name: Auto fix

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  # issues: write

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 22
      PNPM_VERSION: 9

    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v4

      - name: Deps cache (restore)
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./app/node_modules
            ~/.local/share/pnpm/store
          key: pnpm-v${{ env.PNPM_VERSION }}-${{ hashFiles('app/pnpm-lock.yaml') }}
          restore-keys: pnpm-v${{ env.PNPM_VERSION }}-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          #cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install Deps
        run: pnpm install

      - name: Biome
        #if: ${{ success() || failure() }}
        if: ${{ !cancelled() }}
        run: pnpm exec biome check --write
        working-directory: ./app

      - name: Git
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Auto format"
            git push -u origin autofix-${{ github.sha }}

            gh pr create --base ${{ github.ref_name }} --title "Auto format" --body ""
          fi
