name: Check

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 20
      PNPM_VERSION: 9

    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v4

      - name: Deps cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./app/node_modules
            ~/.local/share/pnpm/store
          key: pnpm-v${{ env.PNPM_VERSION }}-${{ hashFiles('app/pnpm-lock.yaml') }}
          restore-keys: pnpm-v${{ env.PNPM_VERSION }}-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          #cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install Deps
        run: pnpm install

      - name: Biome
        #if: ${{ success() || failure() }}
        if: ${{ !cancelled() }}
        run: pnpm exec biome ci

      - name: Type check
        if: ${{ !cancelled() }}
        run: pnpm run typecheck
